name: Test and Deploy App Code

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/deploy-code.yml'

permissions:
  id-token: write
  contents: read

jobs:
  client-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run test

  server-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/server
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm test

  deploy:
    name: Deploy Backend + Frontend
    runs-on: ubuntu-latest
    needs: [client-tests, server-tests]

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::600627336251:role/test01
          aws-region: us-west-2

      # --- Lambda Backend ---
      - name: Zip Lambda
        working-directory: src/server
        run: |
          npm ci --omit=dev
          zip -r ../../express-lambda.zip .

      - name: Upload Lambda to AWS
        run: |
          aws lambda update-function-code \
            --function-name express-backend \
            --zip-file fileb://express-lambda.zip

      # --- Vite Frontend ---
      - name: Build Frontend
        working-directory: src/client
        run: |
          npm ci
          npm run build

      - name: Upload to S3
        run: |
          aws s3 sync src/client/dist s3://vite-frontend-3e0e8078 --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id E17KHQ6K8WJ18J \
            --paths "/*"
